import type { Metadata } from "next";
import { contact } from "./site-data";
import { siteUrl } from "./site-url";

export const performerKeywords = [
  "Arun Guinness",
  "Arun Guiness",
  "Arun Giness",
  "Arun Ginnes",
  "Arun Guinnes",
  "Iron Guinness",
  "Iron Guiness",
  "Arun Guinness artist",
  "Arun Guinness singer",
  "Arun Guinness mimicry artist",
  "Arun Guinness voice artist",
  "Arun Guinness live show",
  "Arun Guinness one man show",
  "Arun Guinness stage show",
  "Arun Guinness booking",
  "book Arun Guinness",
  "Arun Guinness contact number",
  "Arun Guinness Kerala",
  "Arun Guinness Kochi",
  "Arun Guinness Ernakulam",
  "Kerala voice imitation artist",
  "Malayalam voice imitation artist",
  "male female voice singer",
  "male and female voice singer",
  "playback singer voice imitation",
  "Malayalam mimicry singer",
  "Kerala mimicry performer",
  "Kerala live entertainer",
  "Malayalam live entertainer",
  "Indian voice transformation artist",
  "singer mimicry artist Kerala",
  "celebrity voice imitation singer",
  "live vocal mimicry show",
  "one man many voices show",
] as const;

export const soloStageKeywords = [
  "solo stage shows",
  "solo stage show",
  "solo stage performer",
  "solo live stage show",
  "solo musical stage show",
  "solo entertainment show",
  "solo performer for events",
  "book solo stage performer",
  "best solo stage show Kerala",
  "Kerala solo stage shows",
  "Malayalam solo stage show",
  "Malayali solo stage show",
  "one man show Kerala",
  "one man stage show",
  "one man live show",
  "one man musical show",
  "one man entertainment show",
  "one man mimicry show",
  "one man voice show",
  "90 minute one man show",
  "live stage shows",
  "professional stage shows",
  "stage show performer Kerala",
  "stage show artist Kerala",
  "stage show booking Kerala",
  "book stage show artist",
  "live entertainment booking Kerala",
  "musical stage show Kerala",
  "mimicry stage show Kerala",
  "voice imitation stage show",
  "singing and mimicry show",
  "male female voice stage show",
  "playback voice stage show",
  "clean comedy stage show",
  "interactive stage show",
  "audience interaction performer",
  "family friendly stage show",
  "cultural programme performer",
  "cultural stage show Kerala",
  "festival stage show Kerala",
  "Onam stage show performer",
  "Vishu stage show performer",
  "Christmas stage show Kerala",
  "New Year stage show performer",
  "association stage show",
  "Malayali association stage show",
  "Malayalee association stage show",
  "Kerala association stage show",
  "Malayali union stage show",
  "community stage show Malayalam",
  "resident association stage show",
  "club stage show Kerala",
  "school annual day stage show",
  "college fest stage show",
  "campus stage show Kerala",
  "arts day stage show",
  "youth festival stage show",
  "alumni meet stage show",
  "corporate stage show Kerala",
  "company event stage show",
  "award night performer Kerala",
  "inauguration stage performer",
  "private event stage show",
  "wedding entertainment stage show",
  "family event live entertainment",
  "ticketed stage show Kerala",
  "public festival live show",
  "variety musical show Kerala",
  "mega stage show Kerala",
  "guest performance Kerala",
  "custom stage show Kerala",
  "multilingual stage show",
  "Malayalam Tamil Hindi stage show",
  "live singer for stage show",
  "mimicry artist for events",
  "voice artist for live events",
  "entertainment programme booking",
  "stage programme booking",
  "stage show enquiry Kerala",
  "stage entertainer contact Kerala",
] as const;

export const regionalStageKeywords = [
  "Kochi solo stage shows",
  "Kochi solo stage show",
  "Kochi stage shows",
  "stage shows in Kochi",
  "live stage shows Kochi",
  "one man show Kochi",
  "solo performer Kochi",
  "stage show artist Kochi",
  "stage show booking Kochi",
  "live entertainer Kochi",
  "mimicry artist Kochi",
  "voice artist Kochi",
  "singer for events Kochi",
  "musical show Kochi",
  "cultural programme Kochi",
  "corporate event entertainer Kochi",
  "college fest performer Kochi",
  "school annual day performer Kochi",
  "association stage show Kochi",
  "Onam programme Kochi",
  "Ernakulam solo stage show",
  "Ernakulam stage shows",
  "live entertainer Ernakulam",
  "mimicry artist Ernakulam",
  "Kakkanad stage show",
  "Aluva stage show",
  "Angamaly stage show",
  "Perumbavoor stage show",
  "Muvattupuzha stage show",
  "Thrippunithura stage show",
  "Fort Kochi stage show",
  "Mattancherry stage show",
  "Kalamassery stage show",
  "Kerala stage shows",
  "stage shows in Kerala",
  "live shows Kerala",
  "Kerala event entertainer",
  "Malayalam stage shows Kerala",
  "Kottayam stage show",
  "Thrissur stage show",
  "Thiruvananthapuram stage show",
  "Kozhikode stage show",
  "Kannur stage show",
  "Palakkad stage show",
  "Alappuzha stage show",
  "Idukki stage show",
  "Pathanamthitta stage show",
  "Kollam stage show",
  "Malappuram stage show",
  "Wayanad stage show",
  "Kasargod stage show",
  "South India stage show performer",
  "India stage show performer",
  "international stage show performer",
  "stage shows abroad",
  "overseas Malayali stage show",
  "NRI Malayali stage show",
  "Gulf stage show performer",
  "Gulf Malayali association show",
  "Gulf Malayalam stage programme",
  "UAE Malayali stage show",
  "Dubai Malayali stage show",
  "Abu Dhabi Malayali stage show",
  "Sharjah Malayali stage show",
  "Qatar Malayali stage show",
  "Doha Malayali stage show",
  "Kuwait Malayali stage show",
  "Oman Malayali stage show",
  "Muscat Malayali stage show",
  "Bahrain Malayali stage show",
  "Saudi Arabia Malayali stage show",
  "Singapore Malayali stage show",
  "Malaysia Malayali stage show",
  "UK Malayali association show",
  "Europe Malayali association show",
  "Australia Malayali association show",
  "Canada Malayali association show",
  "USA Malayali association show",
  "international Onam stage show",
] as const;

const uniqueKeywords = (...groups: ReadonlyArray<readonly string[]>) =>
  Array.from(new Map(groups.flat().map((keyword) => [keyword.toLowerCase(), keyword])).values());

export const bookingKeywords = uniqueKeywords(soloStageKeywords, regionalStageKeywords);
export const seoKeywords = uniqueKeywords(performerKeywords, bookingKeywords);

type PageMetadataOptions = {
  title: string;
  description: string;
  path: `/${string}` | "/";
  keywords?: readonly string[];
};

export function createPageMetadata({ title, description, path }: PageMetadataOptions): Metadata {
  const socialTitle = title.includes("Arun Guinness") ? title : `${title} | Arun Guinness`;

  return {
    title: { absolute: socialTitle },
    description,
    authors: [{ name: "Arun Guinness", url: siteUrl }],
    creator: "Arun Guinness",
    publisher: "Arun Guinness",
    category: "Live entertainment",
    alternates: { canonical: path },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-image-preview": "large",
        "max-snippet": -1,
        "max-video-preview": -1,
      },
    },
    openGraph: {
      title: socialTitle,
      description,
      url: path,
      siteName: "Arun Guinness",
      type: "website",
      locale: "en_IN",
      images: [{ url: "/opengraph-image", width: 1200, height: 630, alt: "Arun Guinness — Many voices. One unforgettable evening." }],
    },
    twitter: {
      card: "summary_large_image",
      title: socialTitle,
      description,
      images: ["/opengraph-image"],
    },
  };
}

export const siteStructuredData = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": `${siteUrl}/#website`,
      url: siteUrl,
      name: "Arun Guinness",
      description: "Official website for Arun Guinness live stage shows, one-man shows and booking enquiries.",
      inLanguage: "en",
    },
    {
      "@type": "Person",
      "@id": `${siteUrl}/#arun-guinness`,
      name: "Arun Guinness",
      jobTitle: "Singer, voice artist, mimicry performer and live entertainer",
      description: "Kerala-based live performer known for singing in male and female playback styles, voice imitation, mimicry and audience interaction.",
      url: siteUrl,
      telephone: contact.phone,
      address: {
        "@type": "PostalAddress",
        addressLocality: "Kochi",
        addressRegion: "Kerala",
        addressCountry: "IN",
      },
      homeLocation: { "@type": "Place", name: "Kochi, Kerala, India" },
      knowsAbout: ["Live singing", "Voice imitation", "Mimicry", "One-man shows", "Stage entertainment", "Sound engineering"],
      sameAs: [contact.instagram, contact.youtube, contact.facebook],
    },
    {
      "@type": "Service",
      "@id": `${siteUrl}/#stage-show-booking`,
      name: "Arun Guinness Live Stage Show Booking",
      serviceType: "Live stage show booking",
      url: `${siteUrl}/book`,
      description: "Booking service for solo stage shows, one-man shows, campus programmes, association events and international live entertainment.",
      provider: { "@id": `${siteUrl}/#arun-guinness` },
      areaServed: ["Kochi", "Ernakulam", "Kerala", "India", "Worldwide"],
      availableChannel: { "@type": "ServiceChannel", serviceUrl: `${siteUrl}/book` },
    },
  ],
};

export function serializeJsonLd(value: unknown): string {
  return JSON.stringify(value).replace(/</g, "\\u003c");
}
